[[constraint]]
  name = "github.com/docker/go"
  version = "1.5.1-1"

[[constraint]]
  name = "github.com/stretchr/testify"
  version = "1.2.2"

[[constraint]]
  name = "gopkg.in/yaml.v2"
  version = "2.2.1"

[[constraint]]
  name = "github.com/Azure/go-autorest"
  revision = "69b4126ece6b5257e2f9b0017007d2334153655f"

[[constraint]]
  name = "github.com/docker/cli"
  revision = "v18.09.9"

[[override]]
  name = "github.com/docker/distribution"
  revision = "v2.7.1"

[[override]]
  name = "k8s.io/apimachinery"
  revision = "27d36303b655"

[[override]]
  name = "k8s.io/api"
  revision = "95b840bb6a1f"

[[override]]
  name = "k8s.io/client-go"
  revision = "1fbdaa4c8d90"

[[override]]
  name = "k8s.io/kubernetes"
  revision = "kubernetes-1.11.2"

[[override]]
  name = "k8s.io/kube-openapi"
  revision = "d8ea2fe547a448256204cfc68dfee7b26c720acb"

[[override]]
  name = "github.com/docker/compose-on-kubernetes"
  revision = "a6086e2369e39c2058a003a7eb42e567ecfd1f03"

[[override]]
  name = "github.com/containerd/containerd"
  revision = "7f5f1176dd9fb3cc8d3ce5de91759ed3dc969fa2"

[[override]]
  name = "golang.org/x/sys"
  revision = "f49334f85ddcf0f08d7fb6dd7363e9e6d6b777eb"

[prune]
  non-go = true
  unused-packages = true
  go-tests = true
