[[constraint]]
  name = "github.com/docker/go"
  version = "1.5.1-1"

[[constraint]]
  name = "github.com/stretchr/testify"
  version = "1.2.2"

[[constraint]]
  name = "gopkg.in/yaml.v2"
  version = "2.2.1"

[prune]
  non-go = true
  unused-packages = true
  go-tests = true
